apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: azure-event-hub-app
spec:
  build:
    useBuildKit: true
  environments:
    - name: dev
      build:
        from: main
  components:
    - name: web-app
      src: ./web-app
      ports:
        - name: http
          port: 8008
      publicPort: http
      identity:
        azure:
          clientId: "7ef841f8-a263-45ea-8993-683cc6817ae2"
      authentication:
        oauth2:
          clientId: "7ef841f8-a263-45ea-8993-683cc6817ae2"
          credentials: azureWorkloadIdentity
      variables:
        EVENT_HUB_NAMESPACE: radixtest
        EVENT_HUB_NAME: radixtesteventhub
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
        limits:
          cpu: 500m
          memory: 500Mi
    - name: event-hub-consumer
      replicas: 0
      src: ./event-hub-consumer
      secrets:
        - EVENT_HUB_CONNECTION
        - STORAGE_CONNECTION
      variables:
        EVENT_HUB_NAME: radixtesteventhub
        EVENT_HUB_NAMESPACE: radixtest
        BLOB_CONTAINER: events
        CONSUMER_GROUP: "$Default"
        HTTP_POLICY_LOG_LEVEL: WARNING
        EVENT_HUB_LOG_LEVEL: WARNING
        SLEEP_SECONDS: 6
      horizontalScaling:
        minReplicas: 0
        maxReplicas: 1
        triggers:
          - name: azure-event-hub
            azureEventHub:
              eventHubConnectionFromEnv: EVENT_HUB_CONNECTION
              storageConnectionFromEnv: STORAGE_CONNECTION
              container: events
              eventHubNameFromEnv: EVENT_HUB_NAME
              unprocessedEventThreshold: 4
              activationUnprocessedEventThreshold: 2
# Workload identity
#            azureEventHub:
#              authentication:
#                identity:
#                  azure:
#                    clientId: "7ef841f8-a263-45ea-8993-683cc6817ae2"
#              eventHubName: radixtesteventhub
#              eventHubNamespace: radixtest
#              accountName: radixblobtest7
#              container: events
#              unprocessedEventThreshold: 4
#              activationUnprocessedEventThreshold: 2
